export const GET_STICKERS_SEARCH_READ = "GET_STICKERS_SEARCH_READ"
export const GET_STICKERS_SEARCH_READ_SUCCEEDED =
  "GET_STICKERS_SEARCH_READ_SUCCEEDED"
export const GET_STICKERS_SEARCH_READ_FAILED = "GET_STICKERS_SEARCH_READ_FAILED"
